name: Create .xdc release if build steps involve python

on:
  push:
    tags:
    - '*'
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: build .xdc file
      run: |
        pip3 install -r requirements.txt
        python3 build.py -n ${{ github.event.repository.name }}
    - uses: ncipollo/release-action@v1.10
      with:
        artifacts: ${{ github.event.repository.name }}.xdc

