name: Create .xdc Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: build .xdc file
      id: build
      run: |
        wget https://github.com/webxdc/webxdc-dev/raw/master/create-xdc.sh
        chmod +x create-xdc.sh
        ./create-xdc.sh ${{ github.event.repository.name }}
        if [[ ${{ github.event.repository.name }} == *.xdc ]]
        then
          exit 1
        fi
      continue-on-error: true
    - uses: ncipollo/release-action@v1
      if: steps.build.outcome != 'success'
      with:
        artifacts: ${{ github.event.repository.name }}
    - uses: ncipollo/release-action@v1
      if: steps.build.outcome == 'success'
      with:
        artifacts: ${{ github.event.repository.name }}.xdc

